config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'application#home'
  devise_for :authors
  resources :authors, only: [:index, :show]
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
# frozen_string_literal: true

# Creates validations and associations for the devise model Author.
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  has_many :books

  validates_presence_of :first_name, :last_name

  def full_name
    if middle_name.present?
      "#{first_name} #{middle_name} #{last_name}"
    else
      "#{first_name} #{last_name}"
    end
  end
end

app/models/book.rb
# frozen_string_literal: true

# Creates associations and class methods for Author.
class Book < ApplicationRecord
  belongs_to :author

  def citation
    author.middle_name.present? ? citation_with_middle : citation_without
  end

  private

  def citation_with_middle
     cit_beg_blurb + ' ' + author.middle_name + cit_mid_blurb + cit_end_blurb
  end

  def citation_without
    cit_beg_blurb + cit_mid_blurb + cit_end_blurb
  end

  def cit_beg_blurb
    author.last_name + ', ' + author.first_name
  end

  def cit_mid_blurb
    '. ' + title + '. ' + publisher_city + ': ' + publisher + ', '
  end

  def cit_end_blurb
    publish_year.to_s + '. Print.'
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Defines actions for the root page and permitted parameters for the
# devise model
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def home
    render :home
  end

  protected

  def configure_permitted_parameters
    attributes = [
      :first_name, :middle_name, :last_name, :home_town, :home_state, :dob
    ]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end
end

app/controllers/authors_controller.rb
# frozen_string_literal: true

# creates actions outside of devise's purview for authors
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find_by(id: params[:id])

    if !@author.present?
      redirect_to root, error: 'Author not found.'
    end
  end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

# creates actions and validations for Books controller.
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :create_book, only: [:create]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show; end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit; end

  # POST /books
  # POST /books.json
  def create
    respond_to do |format|
      if @book.save
        format.html { redirect_to current_author, notice: create_notice_string }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to current_author, notice: update_notice_string }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy

    respond_to do |format|
      if current_author == @book.author && @book.destroy
        format.html {
          redirect_to current_author,
          notice: destroy_notice_string
        }
      else
        format.html { redirect_to @book, error: destroy_error_string }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # sets up a new book with permitted params
  def create_book
    @book = current_author.books.build(book_params)
  end

  # holds the notice for create
  def create_notice_string
    'Book was successfully created.'
  end

  # holds the update notice string
  def update_notice_string
    'Book was successfully updated.'
  end

  # holds the destroy notice string
  def destroy_notice_string
    'Book was successfully destroyed.'
  end

  # holds the destroy error message
  def destroy_error_string
    'There was an error destroying this book'
  end

  # Never trust parameters from the scary internet, only allow the white
  # list through.
  def book_params
    params.require(:book).permit(:title, :publish_year, :publisher, :publisher_city)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# contains any helper methods for the root views
module ApplicationHelper
end

app/helpers/books_helper.rb
# frozen_string_literal: true

# contains any helper methods for the Books views.
module BooksHelper
end

app/views/application/home.html.erb
<div>
	<p>Welcome to Rails Bookshelf! A Website specifically designed to keep track of author's books.</p>
</div>

app/views/authors/index.html.erb
<h2>Authors</h2>
<ul>
	<% @authors.each do |a| %>
		<%= link_to a.full_name, author_path(a) %>
	<% end %>
</ul>

app/views/authors/show.html.erb
<h2>Author's Details</h2>
<ul>
	<li>Name: <%= @author.full_name %></li>
	<li>Hometown: <%= @author.home_town %>, <%= @author.home_state %></li>
	<li>Birthdate: <%= @author.dob %></li>
</ul>

<% if author_signed_in? && current_author == @author %>
	<%= button_to 'Edit Profile', edit_author_registration_path, :method => :get %>
	<br>
	<%= button_to 'Add Books', new_book_path, :method => :get %>
<% end %>

<h4>Books Published</h4>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Year Published</th>
    </tr>
  </thead>
  <tbody>
  	<% @author.books.each do |book| %>
	    <tr onclick="location.href='<%= book_path(book) %>'"> 
	      <th><%= book.title %></th>
	      <td><%= book.publish_year %></td>
	    </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :publisher %>
    <%= form.text_field :publisher %>
  </div>

  <div class="field">
    <%= form.label :publisher_city, 'City of Publisher Headquarters' %>
    <%= form.text_field :publisher_city %>
  </div>

  <div class="field">
    <%= form.label :publish_year, "Year Published" %>
    <%= form.number_field :publish_year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1> All Books</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Author</th>
      <th scope="col">Year Published</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr onclick="location.href='<%= book_path(book) %>'"> 
        <th><%= book.title %></th>
        <td><%= book.author.full_name %></td>
        <td><%= book.publish_year %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<h4><%= @book.title %></h4>

<ul>
  <li><strong>Author: </strong><%= link_to @book.author.full_name, @book.author %></li>
  <li><strong>Publisher: </strong><%= @book.publisher %></li>
  <li><strong>City of Publisher Headquarters: </strong><%= @book.publisher_city %></li>
  <li><strong>Year Published: </strong><%= @book.publish_year %></li>
</ul>

<% if current_author == @book.author %>
	<%= link_to 'Edit', edit_book_path(@book) %> | 
	<%= link_to 'Delete', book_path(@book), method: :delete, data: {confirm: "Are you sure?"} %> | 
<% end %>
<%= link_to 'Back', url_for(:back) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBookshelf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
          <a class="navbar-brand" href="/">Rails Bookshelf</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <%= link_to "Books", books_path, :class => 'navbar-link'  %> | 
                <%= link_to "Authors", authors_path, :class => 'navbar-link'  %>
                <% if author_signed_in? %>
                   | <%= link_to "#{current_author.first_name}'s Bookshelf", author_path(current_author),  :class => 'navbar-link'  %> | 
                  <%= link_to "Logout", destroy_author_session_path, method: :delete, :class => 'navbar-link'  %>
                <% else %>
                   | <%= link_to "Sign up", new_author_registration_path, :class => 'navbar-link'  %> | 
                  <%= link_to "Login", new_author_session_path, :class => 'navbar-link'  %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
    <div class="main container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
    <div class="container">
      <footer>
          &copy; Brad DA Watson 2019
      </footer>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  </body>
</html>